/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBranchOfficerRouteImport } from './routes/_authenticated/branch-officer'
import { Route as AuthenticatedComingSoonRouteImport } from './routes/_authenticated/coming-soon'
import { Route as AuthenticatedCreditOfficerRouteImport } from './routes/_authenticated/credit-officer'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedLoanOfficerRouteImport } from './routes/_authenticated/loan-officer'
import { Route as AuthenticatedMdRouteImport } from './routes/_authenticated/md'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedBranchOfficerIndexRouteImport } from './routes/_authenticated/branch-officer/index'
import { Route as AuthenticatedBranchOfficerApplicationIdRouteImport } from './routes/_authenticated/branch-officer/$applicationId'
import { Route as AuthenticatedCreditOfficerIndexRouteImport } from './routes/_authenticated/credit-officer/index'
import { Route as AuthenticatedCreditOfficerApplicationIdRouteImport } from './routes/_authenticated/credit-officer/$applicationId'
import { Route as AuthenticatedCreditOfficerDashboardRouteImport } from './routes/_authenticated/credit-officer/dashboard'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers/$customerId'
import { Route as AuthenticatedLoanOfficerIndexRouteImport } from './routes/_authenticated/loan-officer/index'
import { Route as AuthenticatedLoanOfficerApplicationIdRouteImport } from './routes/_authenticated/loan-officer/$applicationId'
import { Route as AuthenticatedLoanOfficerDashboardRouteImport } from './routes/_authenticated/loan-officer/dashboard'
import { Route as AuthenticatedLoanOfficerNewRouteImport } from './routes/_authenticated/loan-officer/new'
import { Route as AuthenticatedMdIndexRouteImport } from './routes/_authenticated/md/index'
import { Route as AuthenticatedBranchOfficerApplicationIdAnalyzeRouteImport } from './routes/_authenticated/branch-officer/$applicationId_.analyze'
import { Route as AuthenticatedBranchOfficerApplicationIdBankStatementRouteImport } from './routes/_authenticated/branch-officer/$applicationId_.bank-statement'
import { Route as AuthenticatedCreditOfficerApplicationIdBankStatementRouteImport } from './routes/_authenticated/credit-officer/$applicationId_.bank-statement'
import { Route as AuthenticatedLoanOfficerApplicationIdBankStatementRouteImport } from './routes/_authenticated/loan-officer/$applicationId_.bank-statement'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBranchOfficerRoute =
  AuthenticatedBranchOfficerRouteImport.update({
    id: '/branch-officer',
    path: '/branch-officer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComingSoonRoute = AuthenticatedComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreditOfficerRoute =
  AuthenticatedCreditOfficerRouteImport.update({
    id: '/credit-officer',
    path: '/credit-officer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoanOfficerRoute =
  AuthenticatedLoanOfficerRouteImport.update({
    id: '/loan-officer',
    path: '/loan-officer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMdRoute = AuthenticatedMdRouteImport.update({
  id: '/md',
  path: '/md',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBranchOfficerIndexRoute =
  AuthenticatedBranchOfficerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBranchOfficerRoute,
  } as any)
const AuthenticatedBranchOfficerApplicationIdRoute =
  AuthenticatedBranchOfficerApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AuthenticatedBranchOfficerRoute,
  } as any)
const AuthenticatedCreditOfficerIndexRoute =
  AuthenticatedCreditOfficerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCreditOfficerRoute,
  } as any)
const AuthenticatedCreditOfficerApplicationIdRoute =
  AuthenticatedCreditOfficerApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AuthenticatedCreditOfficerRoute,
  } as any)
const AuthenticatedCreditOfficerDashboardRoute =
  AuthenticatedCreditOfficerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedCreditOfficerRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoanOfficerIndexRoute =
  AuthenticatedLoanOfficerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLoanOfficerRoute,
  } as any)
const AuthenticatedLoanOfficerApplicationIdRoute =
  AuthenticatedLoanOfficerApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AuthenticatedLoanOfficerRoute,
  } as any)
const AuthenticatedLoanOfficerDashboardRoute =
  AuthenticatedLoanOfficerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedLoanOfficerRoute,
  } as any)
const AuthenticatedLoanOfficerNewRoute =
  AuthenticatedLoanOfficerNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedLoanOfficerRoute,
  } as any)
const AuthenticatedMdIndexRoute = AuthenticatedMdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMdRoute,
} as any)
const AuthenticatedBranchOfficerApplicationIdAnalyzeRoute =
  AuthenticatedBranchOfficerApplicationIdAnalyzeRouteImport.update({
    id: '/$applicationId_/analyze',
    path: '/$applicationId/analyze',
    getParentRoute: () => AuthenticatedBranchOfficerRoute,
  } as any)
const AuthenticatedBranchOfficerApplicationIdBankStatementRoute =
  AuthenticatedBranchOfficerApplicationIdBankStatementRouteImport.update({
    id: '/$applicationId_/bank-statement',
    path: '/$applicationId/bank-statement',
    getParentRoute: () => AuthenticatedBranchOfficerRoute,
  } as any)
const AuthenticatedCreditOfficerApplicationIdBankStatementRoute =
  AuthenticatedCreditOfficerApplicationIdBankStatementRouteImport.update({
    id: '/$applicationId_/bank-statement',
    path: '/$applicationId/bank-statement',
    getParentRoute: () => AuthenticatedCreditOfficerRoute,
  } as any)
const AuthenticatedLoanOfficerApplicationIdBankStatementRoute =
  AuthenticatedLoanOfficerApplicationIdBankStatementRouteImport.update({
    id: '/$applicationId_/bank-statement',
    path: '/$applicationId/bank-statement',
    getParentRoute: () => AuthenticatedLoanOfficerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/branch-officer': typeof AuthenticatedBranchOfficerRouteWithChildren
  '/coming-soon': typeof AuthenticatedComingSoonRoute
  '/credit-officer': typeof AuthenticatedCreditOfficerRouteWithChildren
  '/documents': typeof AuthenticatedDocumentsRoute
  '/loan-officer': typeof AuthenticatedLoanOfficerRouteWithChildren
  '/md': typeof AuthenticatedMdRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/branch-officer/$applicationId': typeof AuthenticatedBranchOfficerApplicationIdRoute
  '/credit-officer/$applicationId': typeof AuthenticatedCreditOfficerApplicationIdRoute
  '/credit-officer/dashboard': typeof AuthenticatedCreditOfficerDashboardRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/loan-officer/$applicationId': typeof AuthenticatedLoanOfficerApplicationIdRoute
  '/loan-officer/dashboard': typeof AuthenticatedLoanOfficerDashboardRoute
  '/loan-officer/new': typeof AuthenticatedLoanOfficerNewRoute
  '/branch-officer/': typeof AuthenticatedBranchOfficerIndexRoute
  '/credit-officer/': typeof AuthenticatedCreditOfficerIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/loan-officer/': typeof AuthenticatedLoanOfficerIndexRoute
  '/md/': typeof AuthenticatedMdIndexRoute
  '/branch-officer/$applicationId/analyze': typeof AuthenticatedBranchOfficerApplicationIdAnalyzeRoute
  '/branch-officer/$applicationId/bank-statement': typeof AuthenticatedBranchOfficerApplicationIdBankStatementRoute
  '/credit-officer/$applicationId/bank-statement': typeof AuthenticatedCreditOfficerApplicationIdBankStatementRoute
  '/loan-officer/$applicationId/bank-statement': typeof AuthenticatedLoanOfficerApplicationIdBankStatementRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/coming-soon': typeof AuthenticatedComingSoonRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/branch-officer/$applicationId': typeof AuthenticatedBranchOfficerApplicationIdRoute
  '/credit-officer/$applicationId': typeof AuthenticatedCreditOfficerApplicationIdRoute
  '/credit-officer/dashboard': typeof AuthenticatedCreditOfficerDashboardRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/loan-officer/$applicationId': typeof AuthenticatedLoanOfficerApplicationIdRoute
  '/loan-officer/dashboard': typeof AuthenticatedLoanOfficerDashboardRoute
  '/loan-officer/new': typeof AuthenticatedLoanOfficerNewRoute
  '/branch-officer': typeof AuthenticatedBranchOfficerIndexRoute
  '/credit-officer': typeof AuthenticatedCreditOfficerIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/loan-officer': typeof AuthenticatedLoanOfficerIndexRoute
  '/md': typeof AuthenticatedMdIndexRoute
  '/branch-officer/$applicationId/analyze': typeof AuthenticatedBranchOfficerApplicationIdAnalyzeRoute
  '/branch-officer/$applicationId/bank-statement': typeof AuthenticatedBranchOfficerApplicationIdBankStatementRoute
  '/credit-officer/$applicationId/bank-statement': typeof AuthenticatedCreditOfficerApplicationIdBankStatementRoute
  '/loan-officer/$applicationId/bank-statement': typeof AuthenticatedLoanOfficerApplicationIdBankStatementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/branch-officer': typeof AuthenticatedBranchOfficerRouteWithChildren
  '/_authenticated/coming-soon': typeof AuthenticatedComingSoonRoute
  '/_authenticated/credit-officer': typeof AuthenticatedCreditOfficerRouteWithChildren
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/loan-officer': typeof AuthenticatedLoanOfficerRouteWithChildren
  '/_authenticated/md': typeof AuthenticatedMdRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/branch-officer/$applicationId': typeof AuthenticatedBranchOfficerApplicationIdRoute
  '/_authenticated/credit-officer/$applicationId': typeof AuthenticatedCreditOfficerApplicationIdRoute
  '/_authenticated/credit-officer/dashboard': typeof AuthenticatedCreditOfficerDashboardRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/loan-officer/$applicationId': typeof AuthenticatedLoanOfficerApplicationIdRoute
  '/_authenticated/loan-officer/dashboard': typeof AuthenticatedLoanOfficerDashboardRoute
  '/_authenticated/loan-officer/new': typeof AuthenticatedLoanOfficerNewRoute
  '/_authenticated/branch-officer/': typeof AuthenticatedBranchOfficerIndexRoute
  '/_authenticated/credit-officer/': typeof AuthenticatedCreditOfficerIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/loan-officer/': typeof AuthenticatedLoanOfficerIndexRoute
  '/_authenticated/md/': typeof AuthenticatedMdIndexRoute
  '/_authenticated/branch-officer/$applicationId_/analyze': typeof AuthenticatedBranchOfficerApplicationIdAnalyzeRoute
  '/_authenticated/branch-officer/$applicationId_/bank-statement': typeof AuthenticatedBranchOfficerApplicationIdBankStatementRoute
  '/_authenticated/credit-officer/$applicationId_/bank-statement': typeof AuthenticatedCreditOfficerApplicationIdBankStatementRoute
  '/_authenticated/loan-officer/$applicationId_/bank-statement': typeof AuthenticatedLoanOfficerApplicationIdBankStatementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/branch-officer'
    | '/coming-soon'
    | '/credit-officer'
    | '/documents'
    | '/loan-officer'
    | '/md'
    | '/settings'
    | '/branch-officer/$applicationId'
    | '/credit-officer/$applicationId'
    | '/credit-officer/dashboard'
    | '/customers/$customerId'
    | '/loan-officer/$applicationId'
    | '/loan-officer/dashboard'
    | '/loan-officer/new'
    | '/branch-officer/'
    | '/credit-officer/'
    | '/customers/'
    | '/loan-officer/'
    | '/md/'
    | '/branch-officer/$applicationId/analyze'
    | '/branch-officer/$applicationId/bank-statement'
    | '/credit-officer/$applicationId/bank-statement'
    | '/loan-officer/$applicationId/bank-statement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/coming-soon'
    | '/documents'
    | '/settings'
    | '/'
    | '/branch-officer/$applicationId'
    | '/credit-officer/$applicationId'
    | '/credit-officer/dashboard'
    | '/customers/$customerId'
    | '/loan-officer/$applicationId'
    | '/loan-officer/dashboard'
    | '/loan-officer/new'
    | '/branch-officer'
    | '/credit-officer'
    | '/customers'
    | '/loan-officer'
    | '/md'
    | '/branch-officer/$applicationId/analyze'
    | '/branch-officer/$applicationId/bank-statement'
    | '/credit-officer/$applicationId/bank-statement'
    | '/loan-officer/$applicationId/bank-statement'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/branch-officer'
    | '/_authenticated/coming-soon'
    | '/_authenticated/credit-officer'
    | '/_authenticated/documents'
    | '/_authenticated/loan-officer'
    | '/_authenticated/md'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/branch-officer/$applicationId'
    | '/_authenticated/credit-officer/$applicationId'
    | '/_authenticated/credit-officer/dashboard'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/loan-officer/$applicationId'
    | '/_authenticated/loan-officer/dashboard'
    | '/_authenticated/loan-officer/new'
    | '/_authenticated/branch-officer/'
    | '/_authenticated/credit-officer/'
    | '/_authenticated/customers/'
    | '/_authenticated/loan-officer/'
    | '/_authenticated/md/'
    | '/_authenticated/branch-officer/$applicationId_/analyze'
    | '/_authenticated/branch-officer/$applicationId_/bank-statement'
    | '/_authenticated/credit-officer/$applicationId_/bank-statement'
    | '/_authenticated/loan-officer/$applicationId_/bank-statement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branch-officer': {
      id: '/_authenticated/branch-officer'
      path: '/branch-officer'
      fullPath: '/branch-officer'
      preLoaderRoute: typeof AuthenticatedBranchOfficerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coming-soon': {
      id: '/_authenticated/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof AuthenticatedComingSoonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/credit-officer': {
      id: '/_authenticated/credit-officer'
      path: '/credit-officer'
      fullPath: '/credit-officer'
      preLoaderRoute: typeof AuthenticatedCreditOfficerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loan-officer': {
      id: '/_authenticated/loan-officer'
      path: '/loan-officer'
      fullPath: '/loan-officer'
      preLoaderRoute: typeof AuthenticatedLoanOfficerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/md': {
      id: '/_authenticated/md'
      path: '/md'
      fullPath: '/md'
      preLoaderRoute: typeof AuthenticatedMdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branch-officer/': {
      id: '/_authenticated/branch-officer/'
      path: '/'
      fullPath: '/branch-officer/'
      preLoaderRoute: typeof AuthenticatedBranchOfficerIndexRouteImport
      parentRoute: typeof AuthenticatedBranchOfficerRoute
    }
    '/_authenticated/branch-officer/$applicationId': {
      id: '/_authenticated/branch-officer/$applicationId'
      path: '/$applicationId'
      fullPath: '/branch-officer/$applicationId'
      preLoaderRoute: typeof AuthenticatedBranchOfficerApplicationIdRouteImport
      parentRoute: typeof AuthenticatedBranchOfficerRoute
    }
    '/_authenticated/credit-officer/': {
      id: '/_authenticated/credit-officer/'
      path: '/'
      fullPath: '/credit-officer/'
      preLoaderRoute: typeof AuthenticatedCreditOfficerIndexRouteImport
      parentRoute: typeof AuthenticatedCreditOfficerRoute
    }
    '/_authenticated/credit-officer/$applicationId': {
      id: '/_authenticated/credit-officer/$applicationId'
      path: '/$applicationId'
      fullPath: '/credit-officer/$applicationId'
      preLoaderRoute: typeof AuthenticatedCreditOfficerApplicationIdRouteImport
      parentRoute: typeof AuthenticatedCreditOfficerRoute
    }
    '/_authenticated/credit-officer/dashboard': {
      id: '/_authenticated/credit-officer/dashboard'
      path: '/dashboard'
      fullPath: '/credit-officer/dashboard'
      preLoaderRoute: typeof AuthenticatedCreditOfficerDashboardRouteImport
      parentRoute: typeof AuthenticatedCreditOfficerRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loan-officer/': {
      id: '/_authenticated/loan-officer/'
      path: '/'
      fullPath: '/loan-officer/'
      preLoaderRoute: typeof AuthenticatedLoanOfficerIndexRouteImport
      parentRoute: typeof AuthenticatedLoanOfficerRoute
    }
    '/_authenticated/loan-officer/$applicationId': {
      id: '/_authenticated/loan-officer/$applicationId'
      path: '/$applicationId'
      fullPath: '/loan-officer/$applicationId'
      preLoaderRoute: typeof AuthenticatedLoanOfficerApplicationIdRouteImport
      parentRoute: typeof AuthenticatedLoanOfficerRoute
    }
    '/_authenticated/loan-officer/dashboard': {
      id: '/_authenticated/loan-officer/dashboard'
      path: '/dashboard'
      fullPath: '/loan-officer/dashboard'
      preLoaderRoute: typeof AuthenticatedLoanOfficerDashboardRouteImport
      parentRoute: typeof AuthenticatedLoanOfficerRoute
    }
    '/_authenticated/loan-officer/new': {
      id: '/_authenticated/loan-officer/new'
      path: '/new'
      fullPath: '/loan-officer/new'
      preLoaderRoute: typeof AuthenticatedLoanOfficerNewRouteImport
      parentRoute: typeof AuthenticatedLoanOfficerRoute
    }
    '/_authenticated/md/': {
      id: '/_authenticated/md/'
      path: '/'
      fullPath: '/md/'
      preLoaderRoute: typeof AuthenticatedMdIndexRouteImport
      parentRoute: typeof AuthenticatedMdRoute
    }
    '/_authenticated/branch-officer/$applicationId_/analyze': {
      id: '/_authenticated/branch-officer/$applicationId_/analyze'
      path: '/$applicationId/analyze'
      fullPath: '/branch-officer/$applicationId/analyze'
      preLoaderRoute: typeof AuthenticatedBranchOfficerApplicationIdAnalyzeRouteImport
      parentRoute: typeof AuthenticatedBranchOfficerRoute
    }
    '/_authenticated/branch-officer/$applicationId_/bank-statement': {
      id: '/_authenticated/branch-officer/$applicationId_/bank-statement'
      path: '/$applicationId/bank-statement'
      fullPath: '/branch-officer/$applicationId/bank-statement'
      preLoaderRoute: typeof AuthenticatedBranchOfficerApplicationIdBankStatementRouteImport
      parentRoute: typeof AuthenticatedBranchOfficerRoute
    }
    '/_authenticated/credit-officer/$applicationId_/bank-statement': {
      id: '/_authenticated/credit-officer/$applicationId_/bank-statement'
      path: '/$applicationId/bank-statement'
      fullPath: '/credit-officer/$applicationId/bank-statement'
      preLoaderRoute: typeof AuthenticatedCreditOfficerApplicationIdBankStatementRouteImport
      parentRoute: typeof AuthenticatedCreditOfficerRoute
    }
    '/_authenticated/loan-officer/$applicationId_/bank-statement': {
      id: '/_authenticated/loan-officer/$applicationId_/bank-statement'
      path: '/$applicationId/bank-statement'
      fullPath: '/loan-officer/$applicationId/bank-statement'
      preLoaderRoute: typeof AuthenticatedLoanOfficerApplicationIdBankStatementRouteImport
      parentRoute: typeof AuthenticatedLoanOfficerRoute
    }
  }
}

interface AuthenticatedBranchOfficerRouteChildren {
  AuthenticatedBranchOfficerApplicationIdRoute: typeof AuthenticatedBranchOfficerApplicationIdRoute
  AuthenticatedBranchOfficerIndexRoute: typeof AuthenticatedBranchOfficerIndexRoute
  AuthenticatedBranchOfficerApplicationIdAnalyzeRoute: typeof AuthenticatedBranchOfficerApplicationIdAnalyzeRoute
  AuthenticatedBranchOfficerApplicationIdBankStatementRoute: typeof AuthenticatedBranchOfficerApplicationIdBankStatementRoute
}

const AuthenticatedBranchOfficerRouteChildren: AuthenticatedBranchOfficerRouteChildren =
  {
    AuthenticatedBranchOfficerApplicationIdRoute:
      AuthenticatedBranchOfficerApplicationIdRoute,
    AuthenticatedBranchOfficerIndexRoute: AuthenticatedBranchOfficerIndexRoute,
    AuthenticatedBranchOfficerApplicationIdAnalyzeRoute:
      AuthenticatedBranchOfficerApplicationIdAnalyzeRoute,
    AuthenticatedBranchOfficerApplicationIdBankStatementRoute:
      AuthenticatedBranchOfficerApplicationIdBankStatementRoute,
  }

const AuthenticatedBranchOfficerRouteWithChildren =
  AuthenticatedBranchOfficerRoute._addFileChildren(
    AuthenticatedBranchOfficerRouteChildren,
  )

interface AuthenticatedCreditOfficerRouteChildren {
  AuthenticatedCreditOfficerApplicationIdRoute: typeof AuthenticatedCreditOfficerApplicationIdRoute
  AuthenticatedCreditOfficerDashboardRoute: typeof AuthenticatedCreditOfficerDashboardRoute
  AuthenticatedCreditOfficerIndexRoute: typeof AuthenticatedCreditOfficerIndexRoute
  AuthenticatedCreditOfficerApplicationIdBankStatementRoute: typeof AuthenticatedCreditOfficerApplicationIdBankStatementRoute
}

const AuthenticatedCreditOfficerRouteChildren: AuthenticatedCreditOfficerRouteChildren =
  {
    AuthenticatedCreditOfficerApplicationIdRoute:
      AuthenticatedCreditOfficerApplicationIdRoute,
    AuthenticatedCreditOfficerDashboardRoute:
      AuthenticatedCreditOfficerDashboardRoute,
    AuthenticatedCreditOfficerIndexRoute: AuthenticatedCreditOfficerIndexRoute,
    AuthenticatedCreditOfficerApplicationIdBankStatementRoute:
      AuthenticatedCreditOfficerApplicationIdBankStatementRoute,
  }

const AuthenticatedCreditOfficerRouteWithChildren =
  AuthenticatedCreditOfficerRoute._addFileChildren(
    AuthenticatedCreditOfficerRouteChildren,
  )

interface AuthenticatedLoanOfficerRouteChildren {
  AuthenticatedLoanOfficerApplicationIdRoute: typeof AuthenticatedLoanOfficerApplicationIdRoute
  AuthenticatedLoanOfficerDashboardRoute: typeof AuthenticatedLoanOfficerDashboardRoute
  AuthenticatedLoanOfficerNewRoute: typeof AuthenticatedLoanOfficerNewRoute
  AuthenticatedLoanOfficerIndexRoute: typeof AuthenticatedLoanOfficerIndexRoute
  AuthenticatedLoanOfficerApplicationIdBankStatementRoute: typeof AuthenticatedLoanOfficerApplicationIdBankStatementRoute
}

const AuthenticatedLoanOfficerRouteChildren: AuthenticatedLoanOfficerRouteChildren =
  {
    AuthenticatedLoanOfficerApplicationIdRoute:
      AuthenticatedLoanOfficerApplicationIdRoute,
    AuthenticatedLoanOfficerDashboardRoute:
      AuthenticatedLoanOfficerDashboardRoute,
    AuthenticatedLoanOfficerNewRoute: AuthenticatedLoanOfficerNewRoute,
    AuthenticatedLoanOfficerIndexRoute: AuthenticatedLoanOfficerIndexRoute,
    AuthenticatedLoanOfficerApplicationIdBankStatementRoute:
      AuthenticatedLoanOfficerApplicationIdBankStatementRoute,
  }

const AuthenticatedLoanOfficerRouteWithChildren =
  AuthenticatedLoanOfficerRoute._addFileChildren(
    AuthenticatedLoanOfficerRouteChildren,
  )

interface AuthenticatedMdRouteChildren {
  AuthenticatedMdIndexRoute: typeof AuthenticatedMdIndexRoute
}

const AuthenticatedMdRouteChildren: AuthenticatedMdRouteChildren = {
  AuthenticatedMdIndexRoute: AuthenticatedMdIndexRoute,
}

const AuthenticatedMdRouteWithChildren = AuthenticatedMdRoute._addFileChildren(
  AuthenticatedMdRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedBranchOfficerRoute: typeof AuthenticatedBranchOfficerRouteWithChildren
  AuthenticatedComingSoonRoute: typeof AuthenticatedComingSoonRoute
  AuthenticatedCreditOfficerRoute: typeof AuthenticatedCreditOfficerRouteWithChildren
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedLoanOfficerRoute: typeof AuthenticatedLoanOfficerRouteWithChildren
  AuthenticatedMdRoute: typeof AuthenticatedMdRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBranchOfficerRoute: AuthenticatedBranchOfficerRouteWithChildren,
  AuthenticatedComingSoonRoute: AuthenticatedComingSoonRoute,
  AuthenticatedCreditOfficerRoute: AuthenticatedCreditOfficerRouteWithChildren,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedLoanOfficerRoute: AuthenticatedLoanOfficerRouteWithChildren,
  AuthenticatedMdRoute: AuthenticatedMdRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
